os:
  - windows

before_install:
  - set -e
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      chocolate install maven --version 3.5.0
      chocolate install jdk8 --verison 8.0.211
    fi

script:
  - mvn clean verify -Prun-its
