os:
  - windows

language: shell

before_install:
  - set -e
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install maven --version 3.5.0
      choco install jdk8 --verison 8.0.211
    fi

script:
  - mvn clean verify -Prun-its
