os:
  - windows

language: shell

cache:
  directories:
    - $HOME/.m2

before_install:
  - set -e
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install jdk8
      Install-ChocolateyEnvironmentVariable "JAVA_HOME" "C:\Program Files\Java\jdk1.8.0_211\"
      RefreshEnv.cmd
      choco install maven
    fi

script:
  - mvn clean verify -Prun-its
