language: shell

os:
  - windows
  - osx
  - linux

dist: xenial

cache:
  directories:
    - $HOME/.m2

before_install:
  - set -e
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install jdk8;
      export JAVA_HOME="C:/Program Files/Java/jdk1.8.0_211";
      choco install maven;
      export M2_HOME="C:/ProgramData/chocolatey/lib/maven"
      export M2=$M2_HOME/bin
      export PATH=$PATH:$M2
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "osx";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt install openjdk-8-jdk;
      sudo apt-get install maven;
    fi

script:
  - C:/ProgramData/chocolatey/lib/maven/bin/mvn verify -Prun-its
