os:
  - windows
  - osx
  - linux

matrix:
  include:
    - os: linux
      dist: xenial

language: shell

cache:
  directories:
    - $HOME/.m2

before_install:
  - set -e
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install jdk8;
      export JAVA_HOME="C:/Program Files/Java/jdk1.8.0_211";
      RefreshEnv.cmd;
      choco install maven;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "osx";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt install default-jdk;
      sudo apt-get install maven;
    fi

script:
  - mvn clean package #verify -Prun-its #-Pupload-coverage-report
