language: shell

os:
  - windows
  - osx
  - linux

dist: xenial

cache:
  directories:
    - $HOME/.m2

before_install:
  - set -e
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install jdk8;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "osx";
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt install openjdk-8-jdk;
    fi

script:
  - ./mvnw verify -Prun-its
