os:
  - windows
  - osx
  - linux

language: shell

cache:
  directories:
    - $HOME/.m2

before_install:
  - set -e
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install jdk8
      export JAVA_HOME="C:/Program Files/Java/jdk1.8.0_211"
      RefreshEnv.cmd
      choco install maven
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      :
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      :
    fi

script:
  - mvn clean verify -Prun-its
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/coverage-reports/jacoco/jacoco.xml
