os:
  - windows

language: shell

cache:
  directories:
    - $HOME/.m2

before_install:
  - set -e
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install jdk8
      echo $JAVA_HOME
      RefreshEnv.cmd
      echo $JAVA_HOME
      choco install maven
    fi

script:
  - mvn clean verify -Prun-its
