os:
  - windows

language: shell

before_install:
  - set -e
  - |
    choco install jdk8
    export JAVA_HOME="C:/Program Files/Java/jdk1.8.0_211"
    RefreshEnv.cmd
    choco install maven

script:
  - mvn clean verify -Prun-its