name: Build and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
      - env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          ./mvnw --batch-mode \
            --file pom.xml \
            -DskipNexusStagingDeployMojo=false \
            -Dsurefire.useFile=false \
            -Prun-it \
            -Pupload-coverage-report \
            deploy
