name: Build and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GPG Private Key
        run: |
          echo ${{ secrets.PGP_ARMORED_PRIVATE_KEY }} | gpg --dearmor | gpg --import --batch
          cp .travis-ci/settings.xml $HOME/.m2/settings.xml
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          ./mvnw --batch-mode --file pom.xml -DskipNexusStagingDeployMojo=false -Dsurefire.useFile=false -Prun-its -Pupload-coverage-report deploy
