name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [ windows-2019, windows-2022, ubuntu-18.04, ubuntu-20.04, macos-11, macos-12 ]
        include:
          - os: windows-2016
            mvnw: .\mvnw.cmd
          - os: windows-2019
            mvnw: .\mvnw.cmd
          - os: windows-2022
            mvnw: .\mvnw.cmd
          - os: ubuntu-18.04
            mvnw: ./mvnw
          - os: ubuntu-20.04
            mvnw: ./mvnw
          - os: macos-10.15
            mvnw: ./mvnw

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build
        run: ${{ matrix.mvnw }} --batch-mode verify

      - name: Upload JaCoCo report
        uses: 'actions/upload-artifact@v3'
        with:
          name: jacoco-${{ matrix.os }}
          path: target/site/jacoco-merged-test-coverage-report/jacoco.xml
          retention-days: 5

  aggregate-jacoco-reports:

    needs: build

    runs-on: ubuntu-18.04

    steps:
      - name: Download all JaCoCo reports
        uses: actions/download-artifact@v2

      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: jacoco-windows-2016/jacoco.xml, jacoco-windows-2019/jacoco.xml, jacoco-windows-2022/jacoco.xml, jacoco-ubuntu-18.04/jacoco.xml, jacoco-ubuntu-20.04/jacoco.xml, jacoco-macos-10.15/jacoco.xml
