name: Build and Deploy

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          ./mvnw --batch-mode --file pom.xml -Dsurefire.useFile=false -Prun-its -Pupload-coverage-report package
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.PGP_ARMORED_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Maven settings.xml file
        run: |
          mkdir -p $HOME/.m2
          cp .github/workflows/.m2/settings.xml $HOME/.m2/settings.xml
      - name: Deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          ./mvnw --batch-mode --file pom.xml -DskipTests -DskipNexusStagingDeployMojo=false deploy
