name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [windows-2016, windows-2019, ubuntu-18.04, ubuntu-20.04]
        mvnw: [./mvnw]
        include:
          - os: windows-2016
            mvnw: .\mvnw.cmd
          - os: windows-2019
            mvnw: .\mvnw.cmd

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Build
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: ${{ matrix.mvnw }} --batch-mode "-Dsurefire.useFile=false" "-Prun-its" "-Pupload-coverage-report" verify
