name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.PGP_ARMORED_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Maven settings.xml file
        run: |
          mkdir -p $HOME/.m2
          cp .github/workflows/.m2/settings.xml $HOME/.m2/settings.xml
      - name: Deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          ./mvnw --batch-mode \
            --file pom.xml \
            -DskipTests \
            -DskipNexusStagingDeployMojo=false \
            deploy
